apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  type: ClusterIP
  selector:           
      component: angular-deployment-component
  ports:
    - port: 3000
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment    
metadata:
  name: angular-deployment
spec:
  selector:
    matchLabels:
      component: angular-deployment-component
  replicas: 1
  template:
    metadata:
      labels:
        component: angular-deployment-component
    spec:
      containers:
        - name: angular-deployment-component
          image: satpal101070/frontendimage:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
